# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('web', models.URLField()),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('nComentario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hoteles')),
            ],
        ),
    ]
