# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteles',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='categoria',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='subcategoria',
            field=models.TextField(default=''),
        ),
    ]
