# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_auto_20160603_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('alojamiento', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('contenido', models.TextField(default='')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hoteles')),
            ],
        ),
    ]
