# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_colecciones_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecciones',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
