# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0005_auto_20160614_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Css',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('color', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=32)),
            ],
        ),
    ]
