# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0006_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
